### ISSUE TITLE
How to obtain synthetic foggy cityscape dataset?

### ISSUE THREAD

**Issue by waterbearbee** [WERush/SCDA#2]
Hello,
I have encountered a problem with processing the foggy cityscape datasets and I want to ask you for help. The official website of foggy cityscape only provides transmittance maps. I failed to combine it with the real clear-weather image to obtain the synthetic foggy image. So I would like to ask how to correctly generate the synthetic foggy cityscape dataset.

**Comment by WERush** [comment]
Hi, @waterbearbee 

For the foggy-cityspaces dataset, you need to send the email to cityspaces-team for requesting the additional data (leftImg8bit_trainvaltest_foggy.zip).
Please refer to the [URL](https://www.cityscapes-dataset.com/downloads/).

**Comment by waterbearbee** [comment]
Thank you for your reply. I can download the dataset on the http://people.ee.ethz.ch/~csakarid/SFSU_synthetic/, but only leftImg8bit_trainvaltest_transmittance.zip is provided  and we cannot obtain leftImg8bit_trainvaltest_foggy.zip directly.

**Comment by WERush** [comment]
I could download the RGB foggy images directly after the cityscapes-team replies the email. They would give you an URL to download the RGB images directly.
