### ISSUE TITLE
KITTI to cityscapes

### ISSUE THREAD

**Issue by yh673025667** [WERush/SCDA#3]
Hi,Xinge
In your paper, table 4. shows that car AP is 42.5(TYPE-3), which source domain is KITTI, and target domain is cityscapes.
But i have only achieved car AP 35.3,my training meta file is KITTI that only has car annotations, validation meta file is cityscapes that also only has car annotations.

I am very confused about this problem.Could you share your training details about KITTI->cityscapes? Thanks very much:)

**Comment by WERush** [comment]
Hi, @yh673025667,

I have uploaded the meta_file of kitti_dataset in this [URL](https://drive.google.com/drive/folders/1Cv6pLJh0E5elvhhTcXaH6eZXDvN8KfEX).
